name: ssvgp
channels:
  - conda-forge
dependencies:
  - python=3.11

  # core numerical stack
  - numpy=2.3.*
  - scipy=1.16.*
  - matplotlib=3.10.*
  - scikit-learn=1.7.*

  # notebook stack
  - notebook=7.4.*
  - jupyterlab=4.4.*
  - ipython=9.*

  - pip
